module.exports = {
    USE_NOT_FOUND: 'USER_NOT_FOUND',
    PASSWORD_INCORRECT: 'PASSWORD_INCORRECT',
    LOGIN_SUCCESS: 'PASSWORD_INCORRECT',
    REQUIRED_FIELD_MISSING: 'REQUIRED_FIELD_MISSING',
    ENTITY_ALREAY_EXISTS: 'ENTITY_ALREAY_EXISTS',
    TOKEN_ERROR: 'TOKEN_ERROR',
    UNAUTHORIZED: 'UNAUTHORIZED',
    NO_TOKEN_PROVIDED: 'NO_TOKEN_PROVIDED',
};
